### ISSUE TITLE
LatoCode infringes the license and trademark of Lato

### ISSUE THREAD

**Issue by twardoch** [paul-go/LatoCode#1]
@paul-go , 

the Lato fonts are released under the SIL OFL license with the Reserved Font Name "Lato". Lato is also the trademark of the publisher tyPoland Łukasz Dziedzic. The license of the Lato fonts allows you to create derivatives of the fonts but those derivatives **must not** contain the term `Lato` in its name.

Currently, your project **infringes the license and trademark** of the Lato fonts. Please adjust the name of this project and the fonts, or remove this repository.

The OFL states: 

> "Reserved Font Name" refers to any names specified as such after the
copyright statement(s).
> 3) No Modified Version of the Font Software may use the Reserved Font
Name(s) unless explicit written permission is granted by the corresponding
Copyright Holder. This restriction only applies to the primary font name as
presented to the users.

The [OFL FAQ](https://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web) clarifies: 

> Question: 5.1 What are Reserved Font Names?

> Answer: These are font names, or portons of font names, that the author has chosen to reserve for use only with the Original Version of the font, or for Modified Version(s) created by the original author.

> Question: 5.5 So what should I, as an author, identify as Reserved Font Names?

> Answer: Original authors are encouraged to name their fonts using clear, distinct names, and only declare the unique parts of the name as Reserved Font Names. For example, the author of a font called "Foobar Sans" would declare "Foobar" as a Reserved Font Name, but not "Sans", as that is a common typographical term, and may be a useful word to use in a derivative font name. Reserved Font Names should also be single words for simplicity and legibility. A font called "Flowing River" should have Reserved Font Names "Flowing" and "River", not "Flowing River". You also need to be very careful about reserving font names which are already linked to trademarks (whether registered or not) which you do not own.

Regards
Adam Twardoch
team Lato fonts

**Comment by paul-go** [comment]
(Taken private)
